---
- name: Apply common configurations
  hosts: all
  become: yes
  roles:
    - common

- name: Configure WebServers
  hosts: webserver
  become: yes
  roles:
    - web

- name: Configure DBServers
  hosts: dbserver
  become: yes
  roles:
    - db
